export interface ProjectTemplate {
  id: string;
  name: string;
  description: string;
  framework: string;
  files: { path: string; content: string }[];
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'react-vite',
    name: 'React + Vite',
    description: 'Modern React app with Vite bundler',
    framework: 'react',
    files: [
      {
        path: 'package.json',
        content: JSON.stringify(
          {
            name: 'my-app',
            private: true,
            version: '0.0.0',
            type: 'module',
            scripts: {
              dev: 'vite',
              build: 'vite build',
              preview: 'vite preview',
            },
            dependencies: {
              react: '^18.3.1',
              'react-dom': '^18.3.1',
            },
            devDependencies: {
              '@vitejs/plugin-react': '^4.3.0',
              vite: '^5.4.0',
            },
          },
          null,
          2,
        ),
      },
      {
        path: 'index.html',
        content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`,
      },
      {
        path: 'src/main.jsx',
        content: `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`,
      },
      {
        path: 'src/App.jsx',
        content: `function App() {
  return (
    <div>
      <h1>Hello World</h1>
    </div>
  )
}

export default App`,
      },
    ],
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    description: 'Full-stack React framework',
    framework: 'nextjs',
    files: [
      {
        path: 'package.json',
        content: JSON.stringify(
          {
            name: 'my-app',
            version: '0.1.0',
            private: true,
            scripts: {
              dev: 'next dev',
              build: 'next build',
              start: 'next start',
            },
            dependencies: {
              next: '14.2.0',
              react: '^18.3.1',
              'react-dom': '^18.3.1',
            },
          },
          null,
          2,
        ),
      },
      {
        path: 'app/page.tsx',
        content: `export default function Home() {
  return (
    <main>
      <h1>Hello World</h1>
    </main>
  )
}`,
      },
      {
        path: 'app/layout.tsx',
        content: `export const metadata = {
  title: 'My App',
  description: 'Generated by AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`,
      },
    ],
  },
];
