export enum AgentTaskStatus {
  PENDING = 'PENDING',
  PLANNING = 'PLANNING',
  DEVELOPING = 'DEVELOPING',
  REFACTORING = 'REFACTORING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum AgentStepStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}
